import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '/app/globals.css'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sky Power',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <div className="content-container">
          {children}
        </div>
        {/* <Footer/> */}
      </body>
    </html>
  )
}
